In [4]:
#ExerciceXp/Week3
#Exercice1
#Création d'un tableau unidimensionnel numpy
import numpy as np
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Exercice2
import numpy as np
my_list=[3.14,2,17,0,1,2]
tab_array=np.array(my_list,dtype=int)
tab_array


array([ 3,  2, 17,  0,  1,  2])

In [11]:
#Exercice3
#Création d'un tableau numpy de dimension 3*3
import numpy as np
table_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
table_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#Exercice 4
#Créer un tableau numpy 2D de forme (4,5) rempli de nombres aléatoires
table_two_dim=np.random.rand(4,5)
table_two_dim

array([[0.66037344, 0.58098396, 0.10307577, 0.70793169, 0.51328763],
       [0.5482367 , 0.27557167, 0.69729229, 0.43219358, 0.41123292],
       [0.06123571, 0.24268158, 0.59834965, 0.11109282, 0.15450567],
       [0.16763877, 0.25883456, 0.18882052, 0.4417121 , 0.15240622]])

In [14]:
#Exercice 5
#Sélectionner la deuxième ligne d'un tableau numpy 2D
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1]

array([20, 21, 22, 23, 24])

In [18]:
#Exercice 6
#Inverser l'ordre des éléments d'un tableau NumPy 1D
sc_array=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
slice_array=sc_array[::-1]
slice_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Exercicec 7
#Créez une matrice identité 4x4 à l'aide de NumPy
identity_matrix=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
identity_matrix



array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [27]:
#Exercice 8
#Trouvez la somme et la moyenne d'un tableau 1D donné
one_dim_array=np.arange(10)
one_dim_array
sum=one_dim_array.sum()
sum
average=one_dim_array.mean()
average


np.float64(4.5)

In [33]:
#Exercice 9
#Créez un tableau NumPy avec des éléments de 1 à 20 ; puis remodelez-le en une matrice 4x5
tab_num=np.arange(20)
tab_num
#Resharding
tab_num.reshape(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
#Exercice 10
#Extraire tous les nombres impairs d'un tableau NumPy donné.
tabl=np.array([1, 3, 5, 7, 9])
impaires=tabl[tabl%2==1]
print(impaires)

[1 3 5 7 9]
